# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mini2Dx
description: > # this means to ignore newlines until "baseurl:"
  mini2Dx is an open-source beginner-friendly, master-ready framework for rapidly prototyping and building 2D games in Java.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
windows_download_url: 
mac_download_url:
linux_download_url:

# Build settings
destination: ../docs
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
keep_files:
  - javadoc
sitemap:
  filename: "/sitemap.xml"
  include_posts:
    - "/blog/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
